### ISSUE TITLE
Ethernet DMA ring management: Gratuitous interrupt-free regions?

### ISSUE THREAD

**Issue by dnadlinger** [stm32-rs/stm32h7xx-hal#197]
The Ethernet DMA driver places the memory barrier and descriptor tail buffer writes into an interrupt-free region, e.g.:

https://github.com/stm32-rs/stm32h7xx-hal/blob/4ca09fa94af0fed8084633c142767cf6515ed8de/src/ethernet/eth.rs#L322-L331

We didn't have this in the quartiq/stabilizer driver, and I can't think of a good reason for it – what's the story here?

**Comment by richardeoin** [comment]
I can't think of a good rationale for these interrupt-free regions either. The write to `_dtpr` should correspond to a single [ptr::write_volatile](https://doc.rust-lang.org/std/ptr/fn.write_volatile.html) call, and I don't see how that could ever be split into multiple stores. 

There's also interrupt-free regions in the DMA channel initialisation ([here](https://github.com/stm32-rs/stm32h7xx-hal/blob/master/src/ethernet/eth.rs#L127) and [here](https://github.com/stm32-rs/stm32h7xx-hal/blob/master/src/ethernet/eth.rs#L277)), which I think are also unnecessary since the `s[tr]` bits in the `damc[tr]x_cr` registers aren't set until [later](https://github.com/stm32-rs/stm32h7xx-hal/blob/master/src/ethernet/eth.rs#L632).

These could just have been an overly-defensive idea added during development that never got removed. If you're able to successfully test without them then removal is probably the right answer.

**Comment by dnadlinger** [comment]
We are actually using this (or rather, one of the progenitor implementations in quartiq/stabilizer, before that switched to stm32h7xx-hal) without those interrupt-free regions in production. They must have been added later at some point, but I really can't see what the point would be – the DMA engine will continue to run even if interrupts are disabled… I'll post a PR to remove them.
