### ISSUE TITLE
Problem with SPI on STM32H743ZI-Nucleo board

### ISSUE THREAD

**Issue by robamu** [stm32-rs/stm32h7xx-hal#266]
Hello,

I am trying to get a simple SPI example to work on a STM32H743ZI nucleo. I have code that looks very similar to the SPI example provided, it was adapted for the nucleo board and I am also using another SPI instance:

```rs
#![deny(warnings)]
#![no_main]
#![no_std]

use panic_halt as _;

use cortex_m_rt::entry;
use stm32h7xx_hal::{prelude::*, spi, timer};

//use nb::block;

#[entry]
fn main() -> ! {
    let dp = stm32h7xx_hal::stm32::Peripherals::take().unwrap();

    // Constrain and Freeze power
    let pwr = dp.PWR.constrain();
    let pwrcfg = pwr.freeze();

    // Constrain and Freeze clock
    let rcc = dp.RCC.constrain();
    let rcc = rcc.use_hse(8.mhz()).bypass_hse().sys_ck(400.mhz()).pll1_q_ck(100.mhz());
    let ccdr = rcc.freeze(pwrcfg, &dp.SYSCFG);

    // Acquire the GPIOC peripheral. This also enables the clock for
    // GPIOA in the RCC register.
    let gpioa = dp.GPIOA.split(ccdr.peripheral.GPIOA);
    let gpiob = dp.GPIOB.split(ccdr.peripheral.GPIOB);
    // See p.68 STM32Nucleo144 boards datasheet and p.90 STM32h743xI/G datasheet
    let sck = gpioa.pa5.into_alternate_af5();
    let miso = gpioa.pa6.into_alternate_af5();
    let mosi = gpiob.pb5.into_alternate_af5();

    // Initialise the SPI peripheral.
    let mut spi = dp.SPI1.spi(
        (sck, miso, mosi),
        spi::MODE_0,
        1.mhz(),
        ccdr.peripheral.SPI1,
        &ccdr.clocks,
    );

    // Write fixed data
    spi.write(&[0x01, 0x02, 0x03]).unwrap();

    // Configure the timer to trigger an update every second
    let mut timer = timer::Timer::tim1(dp.TIM1, ccdr.peripheral.TIM1, &ccdr.clocks);
    timer.start(1.hz());
    // Echo what is received on the SPI
    //let mut received = 0;
    loop {
        spi.write(&[0x11u8, 0x22, 0x33]).unwrap();
        nb::block!(timer.wait()).unwrap();
        //received = block!(spi.read()).unwrap();
    }
}
```

Unfortunately, nothing is happening on the MOSI and MISO lines. I attached the waveform measured with a logic analyzer
![faulty_spi](https://user-images.githubusercontent.com/31589589/139087154-db100076-08bd-4aa4-b57c-4157347dd469.png)

Does anyone have an idea what might cause this issue? I might look into the register configuration in similar C++ code, but this might be related to a clock issue as well. I checked and double checked the pin connections but everything looks correct there..

**Comment by richardeoin** [comment]
Thanks for reporting! Just to clarify, the choice of PB5 or PA7 depends on the configuration of the solder bridges on your development board. It sounds like PA7 is the right choice for your setup, but someone else might actually need to use PB5 on their board.

Part of the reason for the delays between the bytes are due to inefficient code generation from the Rust compiler in debug mode. In particular there's many peripheral register accesses occurring between each byte, which is slow despite the fast core clock. You can easily reduce that by compiling with the [release profile](https://doc.rust-lang.org/cargo/reference/profiles.html). 

Additionally the implementation of the [embedded-hal Write trait](https://docs.rs/embedded-hal/0.2.6/embedded_hal/blocking/spi/trait.Write.html) in this crate doesn't make use of the SPI peripheral's FIFO, which would completely remove the gaps between each byte. You could use the [send](https://docs.rs/embedded-hal/0.2.6/embedded_hal/spi/trait.FullDuplex.html#tymethod.send) method directly, but remember that it will return before the byte is actually sent over SPI.

**Comment by robamu** [comment]
Ah thanks, this is how it looks like with `release`

![better](https://user-images.githubusercontent.com/31589589/139576419-05775a05-c8c8-4d07-b4ec-11787cf736c9.png)

**Comment by richardeoin** [comment]
Great, it looks similar for me. The current implementation waits for the received byte to be available before starting to load the next byte, hence there's always a few cycles delay between bytes. I've made a PR for a FIFO implementation that removes that problem in https://github.com/stm32-rs/stm32h7xx-hal/pull/269. With that PR and `--release` there should be no gap between each byte.
