### ISSUE TITLE
Timer Tick Frequency is calculated incorrectly

### ISSUE THREAD

**Issue by tolgaparlan** [stm32-rs/stm32h7xx-hal#368]
On a nucleo 144 board, running the [tick_timer.rs](https://github.com/stm32-rs/stm32h7xx-hal/blob/master/examples/tick_timer.rs) example fails seemingly because of a problem with how the prescaler and auto-reload register values are calculated. 

In the `set_tick_freq` function, with a clock frequency of 50MHz, the prescaler is calculated as 49 and auto-reload register is written `0xFFFFFFFF`. 

However this obviously does not trigger an update event at 1MHz as it is supposed to. In fact in practice the update is practically never triggered because of how slow the counter increases.

Calculating the ARR register value as `(CLK/(PSC+1))/FREQ)` shows that we would need to write `1` to this register to get a 1MHz interrupt. (Please correct me if my calculation is off).

**Comment by richardeoin** [comment]
Hi @tolgaparlan . Thanks for reporting!

The behaviour you're describing is actually the intended function of the `set_tick_freq` method. This method configures the timer so that the timer **CNT register increases by 1 at the specified rate**. The ARR value isn't really relevant in this case, but it's set to `0xFFFF_FFFF` for consistency. The method you're looking for is called [`set_freq`](https://docs.rs/stm32h7xx-hal/latest/stm32h7xx_hal/timer/struct.Timer.html#method.set_freq). It will trigger and update event (specifically an underflow event I think) at the specified rate.

Perhaps it's possible to improve the documentation to make this less confusing? It seems like you found this through the examples, so maybe this example should be documented more clearly?
